@startuml

actor User

participant "xor_gate" as XOR
participant "Console" as Console

User -> XOR : SetInput(0, 0)
User -> XOR : SetInput(1, 0)
User -> XOR : GetOutput(0)
XOR -> Console : print("0 0 0")

User -> XOR : SetInput(0, 0)
User -> XOR : SetInput(1, 1)
User -> XOR : GetOutput(0)
XOR -> Console : print("0 1 1")

User -> XOR : SetInput(0, 1)
User -> XOR : SetInput(1, 0)
User -> XOR : GetOutput(0)
XOR -> Console : print("1 0 1")

User -> XOR : SetInput(0, 1)
User -> XOR : SetInput(1, 1)
User -> XOR : GetOutput(0)
XOR -> Console : print("1 1 0")

@enduml